output.tf
=> Outputs required for cloudwatch event trigger

batch_object_tagger.tf, ci/utility/meta.yml
=> Fix IAM issue. ListBucket required on all items

variables.tf
=> Upgrade object tagger

ci/utility/jobs/integration-object-tagging.yml, ci/utility/jobs/preprod-object-tagging.yml, ci/utility/jobs/production-object-tagging.yml, ci/utility/jobs/qa-object-tagging.yml, ci/utility/meta.yml
=> Fix pipeline issues

variables.tf
Signed-off-by: levankirvalidze <levan.kirvalidze@dmwgroup.co.uk>
=> bump version of object tagger to use new release

batch_object_tagger.tf, variables.tf
Signed-off-by: levankirvalidze <levan.kirvalidze@dmwgroup.co.uk>
=> limit prefix to uc.db

object_tagger_monitoring.tf
=> Needs to use arrays

batch_s3_object_tagger_compute_environment.tf, locals.tf, output.tf, terraform.tf.j2, variables.tf
Signed-off-by: levankirvalidze <levankirvalidze@digital.uc.dwp.gov.uk>
=> new compute env and output SG

batch_s3_object_tagger_compute_environment.tf
remove SG rule as it already exists on internal compute side
=> remove SG rule as it already exists on internal compute side

ci/utility/jobs/tag-clive/dev-clive-object-tagging.yml, ci/utility/jobs/tag-clive/integration-clive-object-tagging.yml, ci/utility/jobs/tag-clive/preprod-clive-object-tagging.yml, ci/utility/jobs/tag-clive/production-clive-object-tagging.yml, ci/utility/jobs/tag-clive/qa-clive-object-tagging.yml, ci/utility/jobs/tag-payment-timelines/pt-dev-object-tagging.yml, ci/utility/jobs/tag-payment-timelines/pt-integration-object-tagging.yml, ci/utility/jobs/tag-payment-timelines/pt-preprod-object-tagging.yml, ci/utility/jobs/tag-payment-timelines/pt-production-object-tagging.yml, ci/utility/jobs/tag-payment-timelines/pt-qa-object-tagging.yml, ci/utility/jobs/tag-pdm/dev-object-tagging.yml, ci/utility/jobs/tag-pdm/integration-object-tagging.yml, ci/utility/jobs/tag-pdm/preprod-object-tagging.yml, ci/utility/jobs/tag-pdm/production-object-tagging.yml, ci/utility/jobs/tag-pdm/qa-object-tagging.yml, ci/utility/meta.yml
Signed-off-by: levankirvalidze <levankirvalidze@digital.uc.dwp.gov.uk>
=> pass the correct job for each tagging thing

ci/utility/meta.yml
Signed-off-by: levankirvalidze <levankirvalidze@digital.uc.dwp.gov.uk>
=> remove quotes as it was creating a problem

README.md
=> Add information to readme on how to run object tagging

aviator_object_tagging.yml, ci/groups.yml, ci/jobs/update-pipeline.yml, ci/resources.yml, ci/utility/groups.yml, ci/utility/jobs/tag-pdm/production-object-tagging.yml, ci/utility/jobs/update-pipeline-utility.yml, ci/utility/resources.yml, variables.tf
=> Latest object tagger

ci/utility/jobs/tag-pdm/production-object-tagging.yml, ci/utility/resources.yml
Signed-off-by: Chris Scott-Thomas <chris.scott-thomas@infinityworks.com>
=> Remove PDM tagging timed job

batch_s3_object_tagger_compute_environment.tf, locals.tf, output.tf
Switch to using the new VPCE SG
=> Switch to using the new VPCE SG

batch_s3_object_tagger_compute_environment.tf
=> Remove group

ci/utility/jobs/tag-clive/integration-clive-object-tagging.yml, ci/utility/jobs/tag-clive/preprod-clive-object-tagging.yml, ci/utility/jobs/tag-clive/production-clive-object-tagging.yml, ci/utility/jobs/tag-clive/qa-clive-object-tagging.yml, ci/utility/jobs/tag-payment-timelines/pt-integration-object-tagging.yml, ci/utility/jobs/tag-payment-timelines/pt-preprod-object-tagging.yml, ci/utility/jobs/tag-payment-timelines/pt-production-object-tagging.yml, ci/utility/jobs/tag-payment-timelines/pt-qa-object-tagging.yml, ci/utility/jobs/tag-pdm/integration-object-tagging.yml, ci/utility/jobs/tag-pdm/preprod-object-tagging.yml, ci/utility/jobs/tag-pdm/production-object-tagging.yml, ci/utility/jobs/tag-pdm/qa-object-tagging.yml
Remove unnecessary restrictions on running utility jobs
=> Remove unnecessary restrictions on running utility jobs

variables.tf
=> Release v19

ci/jobs/update-pipeline.yml, output.tf
=> Fix update pipeline

output.tf
Output job definition name to use for the clusters
=> Output job definition name to use for the clusters

variables.tf
=> Raise to v0.0.20 - Partition support

variables.tf
=> Bump to version 0.0.21

locals.tf, variables.tf
=> Back out recent changes

batch_object_tagger.tf, locals.tf, variables.tf
=> Pin tagger version per environment, restore UC prefix

variables.tf
=> Bump to 0.0.22 in all envs but Prod

variables.tf
=> Bump version

variables.tf
=> Bump version in Prod

batch_object_tagger.tf, batch_s3_object_tagger_compute_environment.tf, locals.tf
=> Increase the object tagger available grunt in Preprod - Testing
